### ISSUE TITLE
Package name missing

### ISSUE THREAD

**Issue by lilyclements** [cran/moodlequizR#1]
@WolfgangRolke this is a great package, and it's certainly overdue with using R for Moodle! I was just checking out the shiny app and wanted to give a heads-up. When running `shinymoodlequizR()` I got the error:

```
Warning: Error in library: there is no package called ‘shinyMatrix’
```

Easily fixable my end as a user, but thought I'd just drop a message so you can fix it your end too.

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!
